name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git checkout -b gh-pages
          git add index.html css/style.css
          git commit -m "Deploy index.html and css/style.css to GitHub Pages"
          git push --force origin gh-pages